{
 "title": "Battery Voltage",
 "time": { "from": "2022-03-19T22:37:56.446Z", "to": "2022-03-20T10:37:56.446Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_voltage",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pump over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pump",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pump",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "pump",
     "query": "SELECT \"enabled\" FROM \"awesome_policy\".\"pump\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water heater over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "water_heater",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Heater",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "water_heater",
     "query": "SELECT \"enabled\" FROM \"awesome_policy\".\"pump\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_voltage",
     "query": "SELECT last(\"voltage\") FROM \"david_default\".\"battery_voltage\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air con over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_con",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Con",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "air_con",
     "query": "SELECT \"enabled\" FROM \"awesome_policy\".\"pump\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery_voltage",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crypto over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crypto",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Crypto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "crypto",
     "query": "SELECT \"enabled\" FROM \"awesome_policy\".\"pump\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "enabled" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}